services:
    postgres:
        image: postgres:17
        container_name: postgres-chatapp
        environment:
            - POSTGRES_USER=chatuser
            - POSTGRES_PASSWORD=chatpass
            - POSTGRES_DB=chatdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    chatapp:
        build: .
        container_name: chat_app
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgresql://chatuser:chatpass@postgres:5432/chatdb
            NODE_ENV: production
            PORT: 3000
            JWT_SECRET: dsfdsgfdsgmflkgmfd
            JWT_EXPIRES_IN: 7d
        depends_on:
            - postgres

volumes:
    postgres_data:
